language: c
sudo: required
cache: apt
os: linux

branches:
  only:
    - master

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq ninja valac valadoc libgirepository1.0-dev libgee-0.8 gobject-introspection libgtk-3-dev python3-pip
  - pip3 install meson

script:
  - cmake -DDEBUG=ON -DADD_COVERAGE=ON .
  - make VERBOSE=1 -j2
  - make test
