language: c
cache: apt
dist: trusty
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:vala-team/pp
  - sudo apt-get update -qq
  - sudo apt-get install -qq valac libgee-0.8 gobject-introspection libgtk-3-dev
  - sudo pip install cpp-coveralls
script:
  - mkdir build && cd build
  - cmake .. -DDEBUG=ON -DADD_COVERAGE=ON .
  - make VERBOSE=1 -j2
  - make test
after_success:
  - coveralls --exclude lib --exclude tests
