language: c
sudo: required
cache: apt
os: linux

branches:
  only:
    - master

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq valac valadoc libgirepository1.0-dev libgee-0.8 gobject-introspection libgtk-3-dev python3-pip
  - sudo pip3 install meson

script:
  - mkdir build && meson . build/ && cd build
  - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - ./ninja
