language: c
cache: apt
dist: trusty
os: linux
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq valac valadoc libgirepository1.0-dev libgee-0.8 gobject-introspection libgtk-3-dev
  - sudo pip install cpp-coveralls
script:
  - cmake -DDEBUG=ON -DADD_COVERAGE=ON .
  - make VERBOSE=1 -j2
  - make test
after_success:
  - coveralls --exclude lib --exclude tests
